name: Unit Tests

on: [push]

jobs:
    docker-unit-tests:
        runs-on: ubuntu-latest
        name: Build and run unit tests Docker image
        steps:
        
          - name: Check out this repo
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t amnbkr/unit_test:latest -f Dockerfile .        
          - name: Run image
            run: docker run --rm unit-tests-image
          #- name: Push image
           # run: docker login -u amnbkr -p 12112009@Aa && docker push amnbkr/unit_test:latest            
