name: Unit Tests

on: [push]

jobs:
    docker-unit-tests:
        runs-on: ubuntu-latest
        name: Build and run unit tests Docker image
        steps:
        
          - name: Check out this repo
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t amnbkr/win:latest -f Dockerfile.windows .        
          - name: Run image
            run: docker run --rm amnbkr/win:latest
            
          - name: Push image
            run: docker login -u amnbkr -p 12112009@Aa && docker push amnbkr/win:latest
          - name: test
            run: ls            
